name: Build source and wheel packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3

      - name: Install Python 3.11 on macOS
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew update
          brew install pyenv
          echo 'if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi' >> ~/.zshrc
          source ~/.zshrc
          pyenv install 3.11.0
          pyenv global 3.11.0
          python --version

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-build-wheels-${{ hashFiles('setup.cfg', 'setup.py') }}
          restore-keys: |
            ${{ runner.os }}-build-wheels-

      - name: Install required system packages only for Ubuntu Linux
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt-get update
          sudo apt-get -y upgrade
          sudo apt-get install -y libsecp256k1-dev

      - name: Install required Python packages
        run: |
          python3 -m pip install --upgrade build
          python3 -m pip install --user --upgrade twine

      - name: Build source and wheel packages
        run: |
          python3 -m build

      - name: Install the Python wheel
        run: |
          python3 -m pip install dist/aleph_sdk_python-*.whl

      - name: Import and use the package
        # macOS tests fail this step because they use Python 3.11, which is not yet supported by our dependencies
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          python3 -c "import aleph.sdk"
          python3 -c "from aleph.sdk.chains.ethereum import get_fallback_account; get_fallback_account()"
